"""Configuration for all 17 German Landesärztekammern.

Each entry documents the search URL, form parameters, and HTML structure
for extracting doctor data from that chamber's Arztsuche.
"""

# Search parameter for all chambers
FACHGEBIET = "Plastische und Ästhetische Chirurgie"

KAMMERN = [
    {
        "name": "Baden-Württemberg",
        "kuerzel": "AEKBW",
        "bundesland": "Baden-Württemberg",
        "base_url": "https://www.arztsuche-bw.de",
        "search_url": "https://www.arztsuche-bw.de/index.php",
        "method": "GET",
        "params": {"suchen": "1", "arztgruppe": "alle", "id_fachgruppe": "420"},
        "result_selector": "li.resultrow",
        "name_selector": "dd.name dt",
        "detail_selector": "dd.qualifikation",
        "address_selector": "dd.adresse p.anschrift-arzt",
        "pagination": "start",
        "needs_js": False,
    },
    {
        "name": "Bayern",
        "kuerzel": "BLAEK",
        "bundesland": "Bayern",
        "base_url": "https://www.blaek.de",
        "search_url": "https://www.blaek.de/arztsuche",
        "method": "GET",
        "params": {"fachgebiet": FACHGEBIET},
        "result_selector": ".search-result, .arzt-entry, table.results tr",
        "name_selector": "h3, .name, td:first-child",
        "detail_selector": ".details, .fachgebiet, td:nth-child(2)",
        "address_selector": ".address, .ort, td:nth-child(3)",
        "pagination": "page",
        "needs_js": False,
    },
    {
        "name": "Nordrhein",
        "kuerzel": "AEKNO",
        "bundesland": "Nordrhein-Westfalen",
        "base_url": "https://arztsuche.kvno.de",
        "search_url": "https://arztsuche.kvno.de/",
        "method": "API",
        "params": {"searchText": "Plastische Chirurgie"},
        "result_selector": "N/A",
        "name_selector": "N/A",
        "detail_selector": "N/A",
        "address_selector": "N/A",
        "pagination": None,
        "needs_js": False,
    },
    {
        "name": "Hessen",
        "kuerzel": "AEKHESSEN",
        "bundesland": "Hessen",
        "base_url": "https://arztsuchehessen.de",
        "search_url": "https://arztsuchehessen.de/api/suche",
        "method": "API",
        "params": {"doctorType": "F", "professionDoctor[]": ["267", "266"]},
        "result_selector": "N/A",
        "name_selector": "N/A",
        "detail_selector": "N/A",
        "address_selector": "N/A",
        "pagination": None,
        "needs_js": False,
    },
    {
        "name": "Hamburg",
        "kuerzel": "AEKHH",
        "bundesland": "Hamburg",
        "base_url": "https://aerztekammer-hamburg.org",
        "search_url": "https://aerztekammer-hamburg.org/arztsuche/",
        "method": "GET",
        "params": {"fachgebiet": FACHGEBIET},
        "result_selector": "div.item.margin-bottom, div.item",
        "name_selector": ".item__header .flex1",
        "detail_selector": ".item__inner",
        "address_selector": ".item__inner",
        "pagination": None,
        "needs_js": True,
    },
    {
        "name": "Berlin",
        "kuerzel": "AEKB",
        "bundesland": "Berlin",
        "base_url": "https://www.aerztekammer-berlin.de",
        "search_url": "https://www.aerztekammer-berlin.de/10arzt/15telefonbuch/arzt_finden.html",
        "method": "POST",
        "params": {"fachgebiet": FACHGEBIET},
        "result_selector": "table.result tr, .arzt-entry, .search-result",
        "name_selector": "td:first-child, .name",
        "detail_selector": "td:nth-child(2), .fachgebiet",
        "address_selector": "td:nth-child(3), .ort",
        "pagination": None,
        "needs_js": False,
    },
    {
        "name": "Brandenburg",
        "kuerzel": "LAEKB",
        "bundesland": "Brandenburg",
        "base_url": "https://www.laekb.de",
        "search_url": "https://www.laekb.de/www/arztsuche",
        "method": "GET",
        "params": {"fachgebiet": FACHGEBIET},
        "result_selector": ".search-result, .result-item, table tr",
        "name_selector": "h3, .name, td:first-child",
        "detail_selector": ".fachgebiet, td:nth-child(2)",
        "address_selector": ".address, td:nth-child(3)",
        "pagination": "page",
        "needs_js": False,
    },
    {
        "name": "Bremen",
        "kuerzel": "AEKHB",
        "bundesland": "Bremen",
        "base_url": "https://www.aekhb.de",
        "search_url": "https://www.aekhb.de/arztsuche",
        "method": "GET",
        "params": {"fachgebiet": FACHGEBIET},
        "result_selector": ".search-result, .result-item, table tr",
        "name_selector": "h3, .name, td:first-child",
        "detail_selector": ".fachgebiet, td:nth-child(2)",
        "address_selector": ".address, td:nth-child(3)",
        "pagination": None,
        "needs_js": False,
    },
    {
        "name": "Mecklenburg-Vorpommern",
        "kuerzel": "AEKMV",
        "bundesland": "Mecklenburg-Vorpommern",
        "base_url": "https://www.aek-mv.de",
        "search_url": "https://www.aek-mv.de/arztsuche",
        "method": "GET",
        "params": {"fachgebiet": FACHGEBIET},
        "result_selector": ".search-result, .result-item, table tr",
        "name_selector": "h3, .name, td:first-child",
        "detail_selector": ".fachgebiet, td:nth-child(2)",
        "address_selector": ".address, td:nth-child(3)",
        "pagination": None,
        "needs_js": False,
    },
    {
        "name": "Niedersachsen",
        "kuerzel": "AEKN",
        "bundesland": "Niedersachsen",
        "base_url": "https://www.aekn.de",
        "search_url": "https://www.aekn.de/arztsuche",
        "method": "GET",
        "params": {"fachgebiet": FACHGEBIET},
        "result_selector": ".search-result, .result-item, table tr",
        "name_selector": "h3, .name, td:first-child",
        "detail_selector": ".fachgebiet, td:nth-child(2)",
        "address_selector": ".address, td:nth-child(3)",
        "pagination": "page",
        "needs_js": False,
    },
    {
        "name": "Rheinland-Pfalz",
        "kuerzel": "LAEKRLP",
        "bundesland": "Rheinland-Pfalz",
        "base_url": "https://www.laek-rlp.de",
        "search_url": "https://www.laek-rlp.de/fuer-patienten/arztsuche",
        "method": "GET",
        "params": {"fachgebiet": FACHGEBIET},
        "result_selector": ".search-result, .result-item, table tr",
        "name_selector": "h3, .name, td:first-child",
        "detail_selector": ".fachgebiet, td:nth-child(2)",
        "address_selector": ".address, td:nth-child(3)",
        "pagination": None,
        "needs_js": False,
    },
    {
        "name": "Saarland",
        "kuerzel": "AEKSL",
        "bundesland": "Saarland",
        "base_url": "https://www.aerztekammer-saarland.de",
        "search_url": "https://www.aerztekammer-saarland.de/aerzte/informationenfueraerzte/arztsuche/",
        "method": "POST",
        "params": {"s": FACHGEBIET},
        "result_selector": "article.entry.leftpad.single",
        "name_selector": "h2.entry-title",
        "detail_selector": "span.entry-cats",
        "address_selector": ".entry-content .col-md-6:first-child",
        "pagination": None,
        "needs_js": True,
    },
    {
        "name": "Sachsen",
        "kuerzel": "SLAEK",
        "bundesland": "Sachsen",
        "base_url": "https://www.slaek.de",
        "search_url": "https://www.slaek.de/de/04/arztsuche.php",
        "method": "GET",
        "params": {"fachgebiet": FACHGEBIET},
        "result_selector": ".search-result, .result-item, table.arztliste tr",
        "name_selector": "h3, .name, td:first-child, a",
        "detail_selector": ".fachgebiet, td:nth-child(2)",
        "address_selector": ".address, td:nth-child(3)",
        "pagination": "page",
        "needs_js": False,
    },
    {
        "name": "Sachsen-Anhalt",
        "kuerzel": "AEKSA",
        "bundesland": "Sachsen-Anhalt",
        "base_url": "https://www.aeksa.de",
        "search_url": "https://www.aeksa.de/arztsuche",
        "method": "GET",
        "params": {"fachgebiet": FACHGEBIET},
        "result_selector": ".search-result, .result-item, table tr",
        "name_selector": "h3, .name, td:first-child",
        "detail_selector": ".fachgebiet, td:nth-child(2)",
        "address_selector": ".address, td:nth-child(3)",
        "pagination": None,
        "needs_js": False,
    },
    {
        "name": "Schleswig-Holstein",
        "kuerzel": "AEKSH",
        "bundesland": "Schleswig-Holstein",
        "base_url": "https://www.aeksh.de",
        "search_url": "https://www.aeksh.de/arztsuche",
        "method": "GET",
        "params": {"fachgebiet": FACHGEBIET},
        "result_selector": ".search-result, .result-item, table tr",
        "name_selector": "h3, .name, td:first-child",
        "detail_selector": ".fachgebiet, td:nth-child(2)",
        "address_selector": ".address, td:nth-child(3)",
        "pagination": None,
        "needs_js": False,
    },
    {
        "name": "Thüringen",
        "kuerzel": "LAEKTH",
        "bundesland": "Thüringen",
        "base_url": "https://www.laek-thueringen.de",
        "search_url": "https://www.laek-thueringen.de/arztsuche",
        "method": "GET",
        "params": {"fachgebiet": FACHGEBIET},
        "result_selector": ".search-result, .result-item, table tr",
        "name_selector": "h3, .name, td:first-child",
        "detail_selector": ".fachgebiet, td:nth-child(2)",
        "address_selector": ".address, td:nth-child(3)",
        "pagination": None,
        "needs_js": False,
    },
    {
        "name": "Westfalen-Lippe",
        "kuerzel": "AEKWL",
        "bundesland": "Nordrhein-Westfalen",
        "base_url": "https://www.aekwl.de",
        "search_url": "https://www.aekwl.de/arztsuche",
        "method": "GET",
        "params": {"fachgebiet": FACHGEBIET},
        "result_selector": ".search-result, .result-item, table tr",
        "name_selector": "h3, .name, td:first-child",
        "detail_selector": ".fachgebiet, td:nth-child(2)",
        "address_selector": ".address, td:nth-child(3)",
        "pagination": "page",
        "needs_js": False,
    },
]
